docker_image: "lblod/poc-ai-airflow-ner:latest"
docker_host: "tcp://docker-socket-proxy:2375"
auto_remove: "force"
network_mode: "bridge"
mounts:
    - target: "data"
      source: "ner-data"
    - target: "models"
      source: "poc-ai-deployment_model_store"
sparql_endpoint: "http://192.168.6.152:8892/sparql"
load_query: >
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX dct: <http://purl.org/dc/terms/>
    PREFIX soic: <http://rdfs.org/sioc/ns#>
    PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>


    SELECT DISTINCT ?thing ?text WHERE {
        ?thing a <http://rdf.myexperiment.org/ontologies/base/Submission>; prov:generated/dct:hasPart ?part.    
        ?part soic:content ?text.  
        FILTER NOT EXISTS {  ?thing ext:ingestedml2GrowSmartRegulationsNer "1" }
    }



  
  
  
