docker_image: "lblod/poc-ai-airflow-ner:latest"
docker_host: "tcp://docker-socket-proxy:2375"
auto_remove: "True"
network_mode: "bridge"
mounts:
    - target: "data"
      source: "ner-data"
    - target: "models"
      source: "poc-ai-deployment_model_store"
sparql_endpoint: "http://192.168.6.152:8892/sparql"
load_query: >
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX dct: <http://purl.org/dc/terms/>
    PREFIX soic: <http://rdfs.org/sioc/ns#>
    PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>


    SELECT ?thing ?text WHERE {
        VALUES ?thing {<http://example.com/submissions/10> }
        GRAPH <http://mu.semte.ch/application> {
            ?thing prov:generated ?gen .
            ?gen dct:hasPart ?part.
            ?part soic:content ?text.
        }
    }



  
  
  
